### PR TITLE
Fix fetch not being bound to window anymore

### PR DESCRIPTION
**Pull request by maritz**
#16 actually breaks usage in the browser for me, because the context for the native fetch isn't window anymore after the Object.create(self). 

See https://stackoverflow.com/questions/9677985/uncaught-typeerror-illegal-invocation-in-chrome for some simple illustrations of this problem.

This PR however highlights another problem: The tests don't work.

Currently on master, the webpack tests don't compile properly or something, because the bundle that is created has issues with sinon.  
The browserify tests however have another problem: They always run the non-native version of fetch for me. With this PR they use native when available and this then breaks all tests except the first one in each subset.  
I didn't really look into these though. Can you take a look?

### CODE REVIEW

**Comment by qubyte** [comment]
I see what's going on. I'd rather native fetch never be returned (which is the behaviour before #16). I can fix that PR by doing something like:

```javascript
var self = Object.create(global, {fetch: {value: undefined}});
```

The rest of the feature detection in github/fetch only uses this object to see which properties exist, and does not use `self` for accessing them.

As for the tests, I'll take a look. Thanks for letting me know!

**Comment by qubyte** [comment]
Can you take another look at #16? It should never give you the browser native fetch now. I've also excluded sinon from the test builds.

**Comment by maritz** [comment]
Hm, What's the reasoning behind never returning the native fetch? Shouldn't that be a good thing?

**Comment by qubyte** [comment]
It never has before, so it's not expected. If the user wants native fetch where available, it's easy to do. That said, I might consider a Boolean option to return native fetch and constructors. In that case the wrapper should detect and return fetch etc. before the wrapped code has an opportunity.

**Comment by maritz** [comment]
Alright, makes sense. Are the differences between whatwg-fetch and native documented anywhere? I was only able to find the redirect option.

I removed the .bind(global) and fixed an issue with creating the self object with a readonly fetch property.

Thanks to your changes the tests for webpack and browserify now work again as well and with this PR report 100%.

**Comment by qubyte** [comment]
Thanks for this.

It's less about the differences and more about consistency. On top of that, by delegating a fallback to native fetch to the user, they have a choice. If this module automatically falls back on native fetch then we take that choice from them (unless a fallback option is provided).

**Comment by qubyte** [comment]
Thanks for your patience, this looks good!

**Pull request merged**
