### PR TITLE
Allow passing of self rather than just globally uses it

### PR DESCRIPTION
**Pull request by duclet**
Solution for issue #24.

### CODE REVIEW

**Comment by vovkasm** [comment]
This also fixes this module for react-native!

**Comment by qubyte** [comment]
Good to know. Apologies for taking so long to get back to this!

**Comment by vovkasm** [comment]
Thank you! Also it would be cool to release latest changes to npm ;-)

**Comment by qubyte** [comment]
Released in v4.0.0

**Pull request merged**
