### PR TITLE
Automated tests of the Node support

### PR DESCRIPTION
**Pull request by paulmelnikow**
Depends on #4

### CODE REVIEW

**Comment by qubyte** [comment]
Looks like a conflict in package.json. Should be an easy rebase.

**Comment by paulmelnikow** [comment]
Rebased!

**Comment by paulmelnikow** [comment]
@qubyte What do you think about these tests?

**Comment by qubyte** [comment]
Sorry, long couple of days. I'll take a look tomorrow. :)

**Comment by qubyte** [comment]
It got more busy. I haven't forgotten though!

**Comment by qubyte** [comment]
I probably would have gone with a more unit-like approach and tested that the correct inputs were being passed to node-fetch using sandboxed-module. However, the behavioural approach is robust against changes in the API of node-fetch so your approach wins.

I'm going to merge and make a couple of minor changes. Thanks again!

**Comment by paulmelnikow** [comment]
I was just gonna check in about this. Sweet!

**Pull request merged**
